spring:
  application:
    name: testProj
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  servlet:
    context-path: /api

ujin:
  base-url: https://hck-api.unicorn.icu
  token: ${UJIN_TOKEN}
  page-size: 1000

jwt:
  secret: ${JWT_SECRET}
  ttl-days: 30